### ISSUE TITLE
CI: enable package linting

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-storage#1013]
CI in all active branches of this repository, viz. `snapshot`, `staging`, and `production` should run `elastic-package lint` on all package versions within those branches. 

Note: some very old versions of packages, likely in the `production` branch, may not pass `elastic-package lint`. This is because they were created before `elastic-package lint` was a thing. If so, we'll need to think of a good way to exclude these package versions from linting.

**Comment by jlind23** [comment]
Closing at this repo is now deprecated.
