### ISSUE TITLE
Discuss: Purpose of this repository

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-storage#1014]
Currently this repository (https://github.com/elastic/package-storage) serves two purposes:
- as a backing store for packages served by the Elastic Package Registry service, and
- as a development area for some packages, particularly the `snapshot` branch

I think it would be good to have a discussion if we want to keep this dual purpose for this repository or only have it be a backing store for the Elastic Package Registry service.

**Comment by mtojek** [comment]
I think we agree internally only for this:
> as a backing store for packages served by the Elastic Package Registry service, and

Any package development will be forbidden in the Package Storage v2.
