### ISSUE TITLE
Cleanup old packages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#115]
Before we hit 7.9, we should use the opportunity to clean up all the package versions we had over the last month. For each package, only the most recent version should be left.

This means, the production branch needs to be cleaned up.

**Comment by mtojek** [comment]
@ruflin I think we already did this?

**Comment by ruflin** [comment]
Yes, this can be closed. The question is probably if we should do it again shortly before the release?

**Comment by EricDavisX** [comment]
I might ask us not to delete more from Prod at this point, we're at the End of the cycle for 7.9 - its... too late.  just a QA / release biased 2 cents.

**Comment by ruflin** [comment]
@EricDavisX Understood. The only package I'm tempted to remove is `crowdstrike` as older versions are in beta: https://epr.elastic.co/search I don't think this is intentional @adriansr might be able to comment. Before we can remove it, we need of course a newer version ...

**Comment by ph** [comment]
@adriansr Could you comment on the above?

**Comment by ruflin** [comment]
As by now we shipped 7.9, it is kind of too late to remove the packages. But as we will have a new registry with 7.10, we can follow up here.

**Comment by ruflin** [comment]
@mtojek @adriansr @fearful-symmetry I'm following up here now as in the 7.10 registry we have the following packages showing up when not run with `experimental=true`:

```
[
  {
    "name": "crowdstrike",
    "title": "CrowdStrike",
    "version": "0.1.1",
    "release": "beta",
    "description": "CrowdStrike Integration",
    "type": "integration",
    "download": "/epr/crowdstrike/crowdstrike-0.1.1.tar.gz",
    "path": "/package/crowdstrike/0.1.1",
    "icons": [
      {
        "src": "/package/crowdstrike/0.1.1/img/logo-integrations-crowdstrike.svg",
        "title": "CrowdStrike",
        "size": "216x216",
        "type": "image/svg+xml"
      }
    ]
  },
  {
    "name": "endpoint",
    "title": "Elastic Endpoint Security",
    "version": "0.13.1",
    "release": "beta",
    "description": "Protect your hosts with threat prevention, detection, and deep security data visibility.",
    "type": "solution",
    "download": "/epr/endpoint/endpoint-0.13.1.tar.gz",
    "path": "/package/endpoint/0.13.1",
    "icons": [
      {
        "src": "/package/endpoint/0.13.1/img/security-logo-color-64px.svg",
        "size": "16x16",
        "type": "image/svg+xml"
      }
    ]
  },
  {
    "name": "system",
    "title": "System",
    "version": "0.5.3",
    "release": "beta",
    "description": "System Integration",
    "type": "integration",
    "download": "/epr/system/system-0.5.3.tar.gz",
    "path": "/package/system/0.5.3",
    "icons": [
      {
        "src": "/package/system/0.5.3/img/system.svg",
        "title": "system",
        "size": "1000x1000",
        "type": "image/svg+xml"
      }
    ]
  }
]
```

The reason is that these are release as beta. I'll open a PR to change the release type of these to experimental. But me might go even further and remove old versions if needed.

**Comment by ruflin** [comment]
I opened https://github.com/elastic/package-storage/pull/393 but now thinking that it should only change the crowdstrike package? 🤔

**Comment by mtojek** [comment]
Resolving.
