### ISSUE TITLE
Decide what to put on the landing page of package-storage

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#120]
Currently the master branch is shown when landing on the package-storage page. It should be decided on what to show or which branch. See also conversation here: https://github.com/elastic/package-storage/pull/116#issuecomment-653423815

**Comment by mtojek** [comment]
Honestly, I would be for removing master branch at all, not to confuse people. Simply set one of the others as default, e.g. snapshot. WDYT @ycombinator ?

**Comment by ruflin** [comment]
This is one option. But I think there is some value in having a branch where we can put shared things across the branches like docs or scripts. I think @kuisathaverat also has this requirement for CI.

**Comment by ycombinator** [comment]
Yeah, I'm ++ for keeping the `master` branch to use for a landing page and also any other administrative information, scripts, etc. I would, however, make it very clear at the top of the README that no packages should go in this branch and then explain the rest of the branches, etc.

**Comment by kuisathaverat** [comment]
we need the master branch to manage the job definitions in the CI, we could rid of it by making an exception for this repo on the JJBB definition, not a big deal but outside of the regular standard. So we can do it but first, we have to change the job definitions to another branch.

**Comment by mtojek** [comment]
I think we can close it now, as we're planning to move away from the Package Storage v1 so Github repository.
