### ISSUE TITLE
ES version for CI needs to be updated

### ISSUE THREAD

**Issue by P1llus** [elastic/package-storage#1203]
There are some new packages coming in that requires the ES 7.13 release, mostly for its `registered_domain` processors which is new, but also the `community_id` processor which was introduced after the currently used 7.11 version.

Would it be okay to update this or is there a reason to use an older version?

**Comment by P1llus** [comment]
Any thoughts around this one @ycombinator ?

**Comment by ycombinator** [comment]
Yeah, please do it. Looks like it's still set to `7.11.0-SNAPSHOT` which is rather old at this point. I don't see any reason we shouldn't update it to `7.13.0-SNAPSHOT` now. 

While you're at it, would you mind also making the same updates for the `staging` and `production` branches of this repository?

@mtojek @ruflin just a heads up in case you have any concerns.

**Comment by ycombinator** [comment]
PRs to update various branches:
- `snapshot`: https://github.com/elastic/package-storage/pull/1205
- `staging`:
- `production`:
