### ISSUE TITLE
Promote packages between stages

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#123]
# Idea

Use Jenkins pipelines wherever it's possible model the (semi-)continuous delivery solution, that will help with releasing.

# Release stages

With https://github.com/elastic/package-storage/issues/86 the package-storage has 3 release branches: production, staging, snapshot. Packages can be promoted from one branch to an other. This looks as following:

## snapshot -> staging

* select package
* add to staging
* remove from snapshot
* run checks for staging
* run checks for snapshot
* push changes to staging
* push changes to snapshot

Important is that changes are only pushed, if both checks/CI passed.

## staging -> production

* select package
* add to production
* remove from staging
* run checks for production
* run checks for staging
* **open PR to master + CI**
* If PR is merged, remove from staging

---

Notes:

The main difference here is that there is manual PR involved. It would be great if this PR would contain a diff in the PR description between the current and previous package.

An initial draft of such a script for the snapshot->staging part was opened here: https://github.com/elastic/package-storage/pull/110 It does not contain all steps yet.

**Comment by ruflin** [comment]
@ph I assigned you for now so you can push this forward.

**Comment by mtojek** [comment]
I will take care of this.

**Comment by ruflin** [comment]
Thank you!
