### ISSUE TITLE
Automatic deployment of snapshot/staging/production

### ISSUE THREAD

**Issue by mtojek** [elastic/package-storage#1254]
We received a couple of feature requests for this, so let me remind historical reasons behind postponing the decision:
- we don't have any alarms that deployment fails or registry died
- we don't have any mechanism to coordinate deployments (prevent rollout for all stages at once)
- we had an idea to cover this technical debt while we switch to the new registry (no capacity)
- there is only Shaunak and me who can work on this and we didn't have capacity for this. The roadmap is full of stuff right now: https://github.com/orgs/elastic/projects/449

Anyway, I agree it would be cool to introduce this feature if we're not able to build the registry v2 in a reasonable (short) time.

**Comment by fearful-symmetry** [comment]
I wonder, if we don't have time to improve the tooling, we can at least make the deployment process a little more intuitive? I just have a link on slack to the Jenkins pipeline that someone sent me. Even adding a message or link to the tooling, PR, or something might help a little bit.

**Comment by mtojek** [comment]
@fearful-symmetry Would you mind sharing the preferred way here? I can try to introduce few changes, but as you mentioned, it's matter of time.

**Comment by fearful-symmetry** [comment]
So @mtojek, the two ideas I have would be be to either add/generate a link as part of `elastic-package promote`, or to add a link to the description of the PR itself. Perhaps we could use the promotion selection (i.e `staging -> prod` and so on) to generate the correct link?

**Comment by mtojek** [comment]
Just to confirm: are you thinking about these links
https://beats-ci.elastic.co/job/Ingest-manager/job/package-storage/job/production/ 
https://beats-ci.elastic.co/job/Ingest-manager/job/package-storage/job/staging/ 
https://beats-ci.elastic.co/job/Ingest-manager/job/package-storage/job/snapshot/ 

or in general the Relese Distribution pipeline
https://beats-ci.elastic.co/job/Ingest-manager/job/release-distribution/

**Comment by fearful-symmetry** [comment]
So, this is the one I've been using:  https://beats-ci.elastic.co/job/Ingest-manager/job/release-distribution/build

No idea if that's the "right" one though.

**Comment by jlind23** [comment]
Closing at this repo is now deprecated.
