### ISSUE TITLE
Automatic merges of promote/delete PRs

### ISSUE THREAD

**Issue by mtojek** [elastic/package-storage#1255]
Blocker: https://github.com/elastic/package-storage/issues/1254

The goal is to enable automatic promotion/deletion of packages between different storage stages. FYI it's not straightforward due to following reasons:
- "delete PR" should be merged if the new Docker image for "promote" is build by CI
- no concurrent merges across the repository
- if the CI job for "promote PR" fails, we can't proceed with "delete PR"

**Comment by jlind23** [comment]
Closing at this repo is now deprecated.
