### ISSUE TITLE
[BUG] Production packages are failing CI integration tests

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/package-storage#150]
Most of the packages in production are failing in CI's integration tests. An example of the failure can be seen here: https://github.com/elastic/package-storage/pull/149

This is because the ingest manager is now sending its version to the package registry which is excluding the packages. So when the integration tests try to install the packages a 500 is returned indicating that the package doesn't exist in the eyes of the ingest manager.

Example: https://github.com/elastic/package-storage/blob/production/packages/aws/0.1.1/manifest.yml#L12
The ingest manager sends `8.0.0` as the kibana version which does not fit that version constraint.

Either the ingest manager needs to send `8.0.0-SNAPSHOT` and many of the packages will have to update their version constraints to handle the additional `-SNAPSHOT` or we'll need to modify the version constraints on most of the packages in production to not look for `-SNAPSHOT`. I believe this has already been done in staging: https://github.com/elastic/package-storage/blob/staging/packages/aws/0.2.0/manifest.yml#L15

An easier solution might be to promote staging to production.

@ph @mtojek @ruflin @ycombinator

**Comment by ruflin** [comment]
My thinking was that on the Kibana side we have a switch which detects that we are running the SNAPSHOT version and don't send the query param. This will mean, the SNAPSHOT build will always show ALL most recent packages.

**Comment by ruflin** [comment]
I filed an issue on the Kibana side for this: https://github.com/elastic/kibana/issues/73291

**Comment by jonathan-buttner** [comment]
I think this issue is mostly resolved. We just need to remove the `8.0.0` from here: https://github.com/elastic/package-storage/blob/production/testing/main_integration_test.go#L131

And switch these lines to `7.x-SNAPSHOT`?
https://github.com/elastic/package-storage/blob/production/testing/environments/snapshot.yml#L6
https://github.com/elastic/package-storage/blob/production/testing/environments/snapshot.yml#L23

Based on the info here: https://github.com/elastic/package-storage/issues/163#issuecomment-665622551

**Comment by ruflin** [comment]
@jonathan-buttner Yes, but we should go with 7.9.0-SNAPSHOT probably.

**Comment by jonathan-buttner** [comment]
This should be fixed
