### ISSUE TITLE
[DISCUSS] Branch protection rules for the production branch

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-storage#154]
For the `production` branch should we enable the following [branch protection rules](https://github.com/elastic/package-storage/settings/branch_protection_rules/16634832)?
* Require pull request reviews before merging
* Require status checks to pass before merging

**Comment by ycombinator** [comment]
cc: @ruflin @ph @mtojek @jonathan-buttner

**Comment by jonathan-buttner** [comment]
Yeah I agree with both of those suggestions. We should probably fix CI in the production branch first though haha: https://github.com/elastic/package-storage/issues/150

**Comment by ruflin** [comment]
I think I added some protections already, happy to add more.

**Comment by ph** [comment]
Agree on the proposal.

**Comment by ycombinator** [comment]
Sounds like we're in agreement. I just checked and the rules proposed above are not yet applied: https://github.com/elastic/package-storage/settings/branch_protection_rules/16634832. I also see @jonathan-buttner's comment about resolving #150 first so waiting on that before enabling the rules.

**Comment by ruflin** [comment]
@ycombinator I think #150 should not hold us back here anymore as builds are green. Can you take care of the changes?

**Comment by jonathan-buttner** [comment]
@ruflin I think we still need to change a couple things as my promotion of the endpoint v0.12.0 package is failing:
https://github.com/elastic/package-storage/pull/179

**Comment by ruflin** [comment]
See my last comment, I think this is now also fixed.

**Comment by ycombinator** [comment]
I have updated the branch protection rules for the `production` branch as follows:

<img width="942" alt="Screen Shot 2020-08-03 at 4 09 07 PM" src="https://user-images.githubusercontent.com/51061/89235787-ba49b680-d5a3-11ea-9cf9-f3b8f8800d01.png">

If you wish to alter these, go to https://github.com/elastic/package-storage/settings/branch_protection_rules/16634832.

**Comment by ycombinator** [comment]
@mtojek I know you have been working recently on automation around promotion between branches. I hope the above changes do not impact you adversely. If they do, I believe we should try to keep them in place but try to make the necessary exceptions for automation users (e.g. via system accounts/headless users).

@ph @ruflin @mtojek Note that the above protection rules have been applied **only** to the `production` branch. Does it make sense to also apply them to `snapshot` and/or `staging` branches?

**Comment by mtojek** [comment]
Absolutely agree with you, such configuration is a must. If so, I will adjust to it ;)

Should these rules be applied to all branches? I would say - based on consistency, yes.

**Comment by jonathan-buttner** [comment]
> Should these rules be applied to all branches? I would say - based on consistency, yes.

Hmm, since `staging` and `snapshot` are more of testing branches maybe we don't require the review or that it passes testing just in case something breaks in CI?

**Comment by ruflin** [comment]
I still have hopes that some scripts will push to staging and snapshot in the future so I would say no.
