### ISSUE TITLE
[Discuss] What Kibana version should CI run against

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#163]
This issue is to discuss which branches should tests against which Kibana version.

Currently, CI spins up a `8.0.0-SNAPSHOT` cluster and tries to load the packages into. But in reality, all the packages we release are for `^7.9.0`. This means we test against a version which is not actually the one in the end used. Historically this made sense as all the development / major chanegs were in 8.0.0-SNAPSHOT first but now that we are slowing down the pace and features we need are directly in 7.9 and later, I suggest we change against which version we test. This also solves the problem that some packages might not show up in Kibana because of the `^7.9.0` limitation.

**Proposal**

In the ideal case, I think we should test with the minimal version a package supports. Currently for most packages this is 7.9.0-SNAPSHOT. The problem with 7.9.0-SNAPSHOT is that AFAIK it will disappear soonish after 7.9.0 is shipped. This means, each time a new minor is out, we need to update to a new snapshot. This means `7.10.0-SNAPSHOT`. I think this is acceptable. Long term, we should test against multiple versions (released and unreleased once).

The other question was if all branches should use the same version or snapshot should depend on a more recent one. But to have consistency during development, I think it is most predicable if all point to the same version.

**Comment by jonathan-buttner** [comment]
> In the ideal case, I think we should test with the minimal version a package supports. Currently for most packages this is 7.9.0-SNAPSHOT. The problem with 7.9.0-SNAPSHOT is that AFAIK it will disappear soonish after 7.9.0 is shipped. This means, each time a new minor is out, we need to update to a new snapshot. This means 7.10.0-SNAPSHOT. I think this is acceptable. Long term, we should test against multiple versions (released and unreleased once).

I wonder if there's some automated way we could query the docker registry to see what the latest major/minor/patch release is or something and use that? That might reduce some of the maintenance burden of having to change this each time we release the stack.

`7.10.0-SNAPSHOT` sounds good to me.

> The other question was if all branches should use the same version or snapshot should depend on a more recent one. But to have consistency during development, I think it is most predicable if all point to the same version.

Yeah I think consistency would be good. That'll reduce potential confusion about which branch should be using which version.

**Comment by ruflin** [comment]
I remember I asked for something like `7.x-SNAPSHOT` to allow this. Back then it was not possible. Perhaps someone knows if something like this exists now out there? @JoshMock perhaps?

**Comment by JoshMock** [comment]
Not sure if this totally answers your question, but [we do publish snapshot builds to the Docker registry](https://www.docker.elastic.co/r/kibana/kibana?show_snapshots=true).

If you want another artifact that isn't containerized, [the artifacts API](https://artifacts-api.elastic.co/v1/versions/7.10.0-SNAPSHOT/) exposes lots of URLs to tarballs for whatever version you might need.

**Comment by EricDavisX** [comment]
To be able to contribute more, I need a meeting to understand where we are and some nuances I don't understand.  Maybe all I need is a flow-chart of the life-cycle of a package change:
 - what repo it starts in, 
 - what repo it is committed to
 - who approves
 - what registry and systems is it first seen in
 - decision tree for it to be promoted (if it starts at 'SNAPSHOT' as most should)
 - who promotes, and then what systems it should show up in
 - and any special exceptions (like if someone pushes to prod first, intentionally)

I can give my experience with 7.9, that the process followed hasn't exposed the packages in a way that facilitated testing easily, and I know some changes are planned on process side to fix, and maybe we can do some more - but I'd prefer know more before suggesting things.  Should we plan to post updates to here: https://github.com/elastic/package-storage/blob/master/README.md to expand understanding and process?

**Comment by ruflin** [comment]
@JoshMock `kibana:7.x-SNAPSHOT` is exactly what I was looking for. Thank you!

**Comment by ruflin** [comment]
I had a good conversation with @EricDavisX about the current state, how things work together and where we should go. The short summary is: We should build and test against what we release. Today this is 7.9.0(-SNAPSHOT) so this is what we should move forward first.

As soon as we are out with 7.10, we should test 7.9 + 7.10 and have queries for the packages. This list will keep growing and we need to figure out ways how to scale it like running it only daily etc. 

@EricDavisX Does the above make sense?

**Comment by ruflin** [comment]
I now opened PR's against snapshot, staging, production for the following changes. Also the integrations repo https://github.com/elastic/integrations/pull/202 and package-registry tests were also adjusted.

**Comment by EricDavisX** [comment]
yes.  thanks for reviewing.  We will want to discuss the amount and format of communication for when packages are being pushed, but it mostly amounts to having assurance that each package is really ready for 'production'.

**Comment by ruflin** [comment]
Going to close this issue as the changes suggested are implemented.

@EricDavisX We should have a follow up discussion / issue on prod communication and criterias for push. Interested to take this on?

**Comment by EricDavisX** [comment]
uh, late reply - but yes, I can add it to my list o' things to wrangle.  cheers.
