### ISSUE TITLE
Proposal: Use [branch] in PRs as title prefix

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#184]
One thing that I think @ycombinator started is to use `[branch-name]` as a prefix in the PR title to describe what branch it targets. I personally find this very useful to quickly spot against what branch a PR should be and also if the same PR happens three times, differentiate between them.

So this is a proposal that we prefix our PR's with the according branch name like `[snapshot]`.

**Comment by ruflin** [comment]
@ycombinator @jonathan-buttner @mtojek WDYT?

**Comment by ycombinator** [comment]
Haha, I think this was not intentional on my part TBH. It is a result of using https://github.com/sqren/backport 😄

**Comment by ycombinator** [comment]
At any rate, I think it's a nice convention so I'm ++ to following it.

**Comment by jonathan-buttner** [comment]
Sounds good to me!

**Comment by mtojek** [comment]
SGTM!

Already adjusted the one active: https://github.com/elastic/package-storage/pull/187

**Comment by ruflin** [comment]
Seems like we are in agreement then. Will try to add it to our README as convention then.

**Comment by mtojek** [comment]
Once the README is updated, I think we can close this issue.

**Comment by ruflin** [comment]
Yep, good timing. I just opened https://github.com/elastic/package-storage/pull/211
