### ISSUE TITLE
[Discuss] Introduce different package distributions

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#24]
Currently packages are never removed from the package-storage and new packages are only added. At some stage, old packages should archived.

An example here is when a package goes GA and the older versions should not be installed anymore. Then the older packages should be archived (not removed). This could for example be a different directory in the package-storage. These packages would not be served by default but the package-registry could still be configured to pull them in.

**Comment by mtojek** [comment]
We gained some experience with packages delivery and don't see the need of removing packages from storage. Also, Kibana recommends installing the newest supported version and doesn't list old ones.

I will resolve this issue.
