### ISSUE TITLE
Package Storage v2 - Create object storage to store .zip files.

### ISSUE THREAD

**Issue by jlind23** [elastic/package-storage#2774]
The goal of this issue is to create an object storage for future .zip files. We need to decide where to put it, what would be the permissions model and who will maintain it (us vs. infra).

**Comment by mtojek** [comment]
I updated the issue description.

My first thought is an S3 bucket behind Cloudfront or a matching selection from Google Cloud.

Hey @elastic/observablt-robots, do you have any recommendations here? Long story short, we'd like to build a similar place to Artifactory to store packages.

_Feel free to link (convert to) an internal issue if necessary._

**Comment by cachedout** [comment]
> Hey @elastic/observablt-robots, do you have any recommendations here? 

I take it from your mention of Cloudfront that you're expecting a considerable amount of traffic to this endpoint? I think we should clarify the requirements here a bit in terms of exactly what this will be used for, what the security profile needs to be, and what kind of traffic we're expecting and then bring in @elastic/infra-hosting to help us work through options.

**Comment by mtojek** [comment]
Hey @cachedout, your questions are absolutely correct. I will come up with a short design doc providing basic requirements for storage. I don't think we have already defined it to build v1 (based on the Github repository).

**Comment by mtojek** [comment]
@cachedout @jsoriano @jlind23 The document is ready for the first review. Let me know what you think.

**Comment by cachedout** [comment]
@mtojek I have completed my review. Thanks for answering my questions so promptly! It all seems very reasonable. I added some comments about next-steps from the hosting/automation side of things and also added a few questions to the `Open Questions` section at the bottom of the document.

**Comment by mtojek** [comment]
Thank you for reviewing it, Mike! I will take a look at your questions in a moment.

**Comment by mtojek** [comment]
It looks like we can close this issue. I'm working on final polishing in other task.
