### ISSUE TITLE
Recreate base package

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#348]
In 7.8, we had a base package that shipped the default assets to Elasticsearch: https://github.com/elastic/package-storage/tree/experimental/packages/base/0.1.0 The package was removed in 7.9 as the assets are now shipped directly by Elasticsearch.

Upgrading of the assets as soon as they are shipped will still be responsibility of the Ingest Manager. Assuming in 7.10 we add 1 new field to the base templates, users starting with 7.10, will get the template directly from Elasticsearch. But users coming from 7.9 will rely on Ingest Manager to update the template to the 7.10 state.

This issue is to recreate the base package with the current content from Elasticsearch: https://github.com/elastic/elasticsearch/pull/57629 It should also be figured out, where the base package should be for development and how it is ensured, base package and Elasticsearch stay in sync.

**Comment by mtojek** [comment]
@ruflin is it still valid or can we close this one?

**Comment by ruflin** [comment]
@mtojek We do not needed it today but I it will become relevant again as soon as do a change to the base templates. I would like to keep it open as a reminder.

**Comment by mtojek** [comment]
@ruflin bumping up the thread, is it still valid :)?

**Comment by ruflin** [comment]
Yes, this now depends a bit on the conclusions reached in https://github.com/elastic/elasticsearch/pull/64978 But this is a bit on hold at the moment because of other priorities. Lets keep it open.

**Comment by mtojek** [comment]
I guess that we don't need it now, so can we close the issue? @ruflin

**Comment by ruflin** [comment]
😆  I'm closing this issue but actually would argue we still need something similar again in the future. But we can open a new issue when we get there.
