### ISSUE TITLE
Lint packages using elastic-package lint

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-storage#365]
Similar to https://github.com/elastic/integrations/pull/246, it would be great if we could have all packages in this repository automatically linted as part of Jenkins CI [PR](https://beats-ci.elastic.co/job/Beats/job/package-storage/view/change-requests/) and [branch](https://beats-ci.elastic.co/job/Beats/job/package-storage/) build jobs.

Some challenges to overcome:
- Older versions of packages may not conform to package linting rules. This is because these versions pre-date the package specification by quite a long time. Rather than update these package versions — which have already been released — to conform to the specification, we may want to somehow skip linting for them?
- Due to [this line of code](https://github.com/elastic/elastic-package/blob/da01c0ddc01abd0e9759dd9353fc6fa5ae5b37ae/internal/packages/packages.go#L71), the `elastic-package` tool cannot work with the `endpoint` package. We need to either update that line or update the [`type`](https://github.com/elastic/package-storage/blob/snapshot/packages/endpoint/0.15.0/manifest.yml#L11) of the `endpoint` package.

**Comment by ruflin** [comment]
* ++ on the idea of skip linting. I'm sure we find good solutions around using the `format_version` in the future for this. I would even be ok, to update all current packages to be `format_version: 0.9.0` if this makes things easier.
* endpoint type: @jonathan-buttner did you investigate if we could remove the `solution` type or if there is any logic attached to. Assuming moving forward it would also be integrations, again we could use the `format_version` to skip the old packages here.

**Comment by jonathan-buttner** [comment]
@paul-tavares any idea if we use this field in the Security Solution UI: https://github.com/elastic/kibana/blob/master/x-pack/plugins/ingest_manager/common/types/models/epm.ts#L59 ?

Currently the endpoint package has `solution` for the `type` and we'd like to change it to `integration`: https://github.com/elastic/endpoint-package/blob/master/package/endpoint/manifest.yml#L11

**Comment by paul-tavares** [comment]
Jonathan,
No, I don’t think we use it in security_solution. If I remember correctly,
the only value we attempt to get is package `version` (Via Kibana epm API).

/Paul
-- 

___
*Paul Tavares *| Sr. Software Engineer | Elastic / www.elastic.co | Durham,
NC, USA

**Comment by jonathan-buttner** [comment]
> Jonathan, No, I don’t think we use it in security_solution. If I remember correctly, the only value we attempt to get is package `version` (Via Kibana epm API). /Paul --
> […](#)
> ___ *Paul Tavares *| Sr. Software Engineer | Elastic / [www.elastic.co](http://www.elastic.co) | Durham, NC, USA

Thanks Paul! @ycombinator I'm working on a PR to get the endpoint package to pass linting. I don't think I have any concerns with changing the existing packages to `0.9.0`. I guess it wouldn't really make sense to only have the linter run on `format_version: 1.0.1` or something?

**Comment by ycombinator** [comment]
So the way the linter works is it takes the major version from the `format_version` and finds the spec for that major version. And then uses that to validate the package. Essentially, we expect that once a spec's major version is set, we only expect non-breaking changes to the spec from that point forward, until the next major version.

Currently we only have version `1.0.0` of the spec defined. So setting `format_version` to `1.0.1` in a package is no different from the linter's perspective than setting it to `1.0.0` or `1.2.0`. The only way to get the linter to ignore any packages would be for them to set their `format_version` to either `0.9.0` or `2.0.0` or higher. I would go with `0.9.0` otherwise whenever we have a spec versioned `2.0.0` or higher, the endpoint package might suddenly start failing validation.

**Comment by jonathan-buttner** [comment]
Gotcha, that makes sense.

**Comment by jlind23** [comment]
Closing at this repo is now deprecated.
