### ISSUE TITLE
Validate package by installing into Kibana

### ISSUE THREAD

**Issue by ruflin** [elastic/package-storage#40]
Currently when a package is added to the package-storage it is validated by the package-registry to make sure all assets are valid. But there are quite a few validation mechanisms that cannot be executed by the registry itself and are only found when installing the package into Kibana.

It would be nice if on each PR the following could happen only for the packages that were changed:

* Start up Registry
* Start up Stack
* Install Package into Kibana
* Validate that no errors during installation happened

This would make sure no packages end up in the storage which are not compatible with Kibana.

Currently all packages are compatible with the most recent Kibana version, long term it should be evaluated based on the package constraints on which stack version to boot up.

**Comment by ruflin** [comment]
I started a PR related to this: https://github.com/elastic/package-storage/pull/54

**Comment by mtojek** [comment]
@ruflin can this issue be resolved?

**Comment by ruflin** [comment]
Yes, closing as https://github.com/elastic/package-storage/pull/54 was merged.
