### ISSUE TITLE
Package validation and external repos

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/package-storage#76]
This issue is to discuss how to make package registry improvements while keeping the packages in `package-storage` `integrations` and any external package repos in sync.

As we iterate and make improvements to the package registry the valid format of a package changes.

When package validation changes many packages need to be updated to comply with the new format.

The current approach of updating the packages in the `package-storage` repo causes difficulties with keeping them in sync. For example the format of the dashboards changed with this PR: https://github.com/elastic/package-storage/pull/66

The problem with this approach is the endpoint repo is not in sync with those changes because they haven't been applied here: https://github.com/elastic/endpoint-package/tree/master/package/endpoint/kibana

When we officially release the endpoint package we'll need some way of keeping track of the actual version that is in production. Changing the contents of the package in `package-storage` doesn't keep the contents in sync with how we have versioned and tagged the package in our release process.

As more users leverage the package registry with external repos this problem will grow. A temporary solution would be to move the endpoint package into the integration repo so that the package format updates only have to be performed in a single place. 

In addition to keeping different repos in sync we'll want to keep iterating and improving the package registry. We need some way to support a new validation/package formats and old formats at the same time.

I can think of a couple ways to handle this:

1. Leverage the package `format_version` field so that when the registry loads the package it only performs validation on the packages to claim to adhere to a certain version
  - This will probably add a lot of complexity to the package registry to support multiple validation formats
2. Leverage the package `format_version` field so that a particular registry release will only serve the packages that are valid for that particular registry
  - This is also difficult because we'd have to have multiple registry versions running in production
3. Make the changes to the packages so they conform to the new format and bump their version numbers. The old packages will have to be removed/archived.
  - This doesn't seem like a great option either depending on how often we add more validation to the package registry we could be removing/archiving a lot

Any thoughts @ruflin ?

**Comment by nnamdifrankie** [comment]
> Make the changes to the packages so they conform to the new format and bump their version numbers. The old packages will have to be removed/archived.

I do not think that registry or its packages should be mutable once released.

**Comment by ruflin** [comment]
My preference here is definitively on Option 1. We are at the moment doing all these changes to the registry and the package format so hopefully we have to do much fewer in the future. Especially I think breaking changes will not be acceptable anymore for quite some time.

Even though we modify packages in the storage at the moment, I think in the future we should NEVER do this (I'm sure we find an exception). If a package is released, it should not be touched anymore. There will be a time, where some packages are just too old. One option I would like to keep open, is that we can archive certain packages: https://github.com/elastic/package-storage/issues/24 

One thing I realised that could simplify things is that also at some stage, we don't allow to push packages with a certain older `format_version` anymore. So we can even remove the old validation code as we know the old packages were valid for the older versions of Kibana.

**Comment by jonathan-buttner** [comment]
> My preference here is definitively on Option 1. We are at the moment doing all these changes to the registry and the package format so hopefully we have to do much fewer in the future. Especially I think breaking changes will not be acceptable anymore for quite some time.
> 
> Even though we modify packages in the storage at the moment, I think in the future we should NEVER do this (I'm sure we find an exception). If a package is released, it should not be touched anymore. There will be a time, where some packages are just too old. One option I would like to keep open, is that we can archive certain packages: #24
> 
> One thing I realised that could simplify things is that also at some stage, we don't allow to push packages with a certain older `format_version` anymore. So we can even remove the old validation code as we know the old packages were valid for the older versions of Kibana.

Sounds good. Maybe as a stop gap if the endpoint package gets changed in `package-storage` let's ping Franklin and I so we can make the appropriate changes in the endpoint package repo.

**Comment by ruflin** [comment]
@jonathan-buttner Yes, we should really ping the team on such things. I foresee one more case where it might change. Will ping both of you.

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner Yes, we should really ping the team on such things. I foresee one more case where it might change. Will ping both of you.

Thanks @ruflin we appreciate it!
