### ISSUE TITLE
Implement a visualization listing all versions of the packages showing the progression of through the storage phases

### ISSUE THREAD

**Issue by EricDavisX** [elastic/package-storage#892]
I'd like to know what packages are on 'snapshot' storage but are not promoted to staging, and same for those that are on staging but not promoted to production.

A visualization or chat showing each version would help to know / track.  I don't know if this exists somewhere already?  Currently, I'd just query the 3 EPR links and see what shows for a given package, it is a bit messy.

https://epr-snapshot.elastic.co/search?package=system&all=true
https://epr-staging.elastic.co/search?package=system&all=true
https://epr.elastic.co/search?package=system&all=true

would be nice to just see a chart like, for example showing the below.  And anything prettier is acceptable too! The below is accurate as of right now, but it may change when PRs are merged and the storage clusters rolled out, so it hard to stay current to manage it.  Perhaps we could have a Kibana visualization as such, or some git issue that is overwritten / updated regularly with each elastic-package storage job jenkins roll out (or a slack integration just to start):

<table>
<tr>
	<td>
	<td>snapshot
	<td>staging
	<td>production
<tr>
	<td>system-0.10.9
	<td> X
	<td> -
	<td> -
<tr>
	<td>system-0.10.8
	<td> X
	<td> X
	<td> -
<tr>
	<td>system-0.10.7
	<td> X
	<td> X
	<td> X
<tr>
	<td>windows-0.3.1
	<td> X
	<td> X
	<td> -
</table>

This would help us gauge how many iterations we have before shipping code, which can lead to efficiency gains. It also just informs on where we are in the process... if we have something in need attention or that was never merged to 'prod'.

Perhaps overall Integration management at this level isn't the right way to go - but I'm curious how we intend to manage the release cycle when we have larger numbers of changes coming in, and it seems to be manually managed by hand (I guess?) by multiple people involved in the development.

**Comment by EricDavisX** [comment]
@kuisathaverat @mtojek @ruflin @andresrc Just pinging for ideas, what do you think?  Is it something you would maybe be delighted to have or is it not warranted / needed?

**Comment by andresrc** [comment]
it could be interesting, yes.

**Comment by ycombinator** [comment]
++ to having an easy way to detect where packages are in the promotion pipeline.

Until then, here's a three-liner you can run to get effectively the same report, although not as neatly organized as the table.

```
docker run -d --rm --name epr_snapshot docker.elastic.co/package-registry/distribution:snapshot
docker exec -it epr_snapshot sh -c 'find ../packages -mindepth 3 -maxdepth 3 | awk -F\/ "{print \$4\"-\"\$5\"\t\"\$3}" | sort'
docker stop epr_snapshot
```

**Comment by ruflin** [comment]
++, would be nice if there would even be a page or something that is always up-to-date with the current state.

**Comment by kuisathaverat** [comment]
we are making a status page for our services and environments, something automated with PRs that ends in a static page with the info, maybe it fits https://github.com/elastic/observability-system-status/tree/master/themes/cstate. 
I understand you need a place where to see package-registry/distribution deployed on each environment and the packages on each package-registry/distribution deployed, isn't it?

**Comment by EricDavisX** [comment]
The docker command @ycombinator put above is extremely helpful, wow, thanks!  I would love to see that exact output as a start.  a highly desired 2nd phase would be to relate the timing of the given promotion stage's pr merge to the last timestamp the stage was rolled out... one way I envision this being realized would be an indicator (and * perhaps? or a color ) per cell in the table relating to if that package is actually deployed or waiting and will be picked up the next time the stage is deployed.

The docker command helps a lot tho.  :)

**Comment by kuisathaverat** [comment]
quick win https://github.com/elastic/package-storage/pull/939

**Comment by mtojek** [comment]
Considering our roadmap for Package Storage v2, we can go with a quick win and implement something more accurate later.
