### ISSUE TITLE
CI: Prevent _.* folders in packages

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-storage#925]
Folders like `_dev` in packages are intended to exist only for development purposes. They should not exist in _built_ packages, i.e. the results of running `elastic-package build`. And the `package-storage` repo should only contain _built_ packages as it is the backend store for the package registries.

We should add steps in CI for each `package-storage` branch to check that no packages contain folders that match the regex `^_.*` (start with underscore).

**Comment by ycombinator** [comment]
@elastic/observablt-robots Is this something you can help us implement?

**Comment by v1v** [comment]
I'm not familiar with this project, can you please elaborate what's needed? 🙏 
Thanks

**Comment by ycombinator** [comment]
Sure, there are details in this repo's [README](https://github.com/elastic/package-storage/blob/master/README.md) but I'll try to summarize below, keeping in mind the context needed for this specific issue.

This repository (`package-storage`) is the backing persistence store for packages served by the Elastic Package Registry. For the purposes of this discussion, a package is a folder that contains sub-folders and files in it. The files may represent assets intended for loading into various Elastic Stack products like Kibana dashboards, Elasticsearch ingest pipelines, etc. or could be static assets to be shown in the Fleet UI in Kibana like icons or screenshots. 

A package could (and often does) have multiple versions that have been released and served by the Elastic Package Registry. 

Finally, the Elastic Package Registry has three distributions that reflect the maturity of released package versions: `snapshot`, `staging`, and `production` (in increasing order of maturity). There are other distributions too but we can ignore them for the moment.

All of this means that this repo (`package-storage`) is organized as follows:
- It contains three branches — [`snapshot`](https://github.com/elastic/package-storage/tree/snapshot), [`staging`](https://github.com/elastic/package-storage/tree/staging), and [`production`](https://github.com/elastic/package-storage/tree/production), roughly corresponding to the three distributions of the Elastic Package Registry mentioned above.
- Each branch contains package versions intended for the corresponding distribution of the Elastic Package Registry. These can be found in the `packages` folder in each branch. For example, here you can see all the versions of the `system` package in the `snapshot` branch: https://github.com/elastic/package-storage/tree/snapshot/packages/system.
- Each version folder contains the sub-folders and files that make up that version of the package, as explained above.

Now, it was decided **by convention** (cc: @mtojek) that any sub-folders inside packages that start with `_` are reserved for internal use. That is, such folders should never actually be released as part of a package. Since this repository (`package-storage`) contains released versions of packages, we should not see any folders starting with `_` in here, under the `packages` folder of each of the three branches mentioned above. 

So far we have not been enforcing this convention. Consequently a couple of package have sneaked through into this repository (`package-storage`) containing these reserved folders. So I made this issue to check for such folders when CI runs in each of the three branches and fail if such folders are found.

Hope that helps, happy to answer any follow up questions. Thanks!

**Comment by ycombinator** [comment]
@v1v Let me know if my previous comment makes sense or if you have any questions. Thanks!

**Comment by v1v** [comment]
IIUC, you only want to run some pre-validation and report if there is a folder with the above format in the change-set. If that's the case, there is a shared library steps that can help with:

- https://github.com/elastic/apm-pipeline-library/blob/master/vars/isGitRegionMatch.txt

Snippet:

```
     whenTrue(isGitRegionMatch(patterns: ["^_.*"])) {
         error('_dev in packages are intended to exist only for development purposes.')
     }
```

The above step uses the git diff from the existing commit versus the target branch. If the above is not something useful. I wonder if those validations should be delegated to the build system (a new goal for instance `validate`), could be called within the pipeline itself, then the implementation details are not in the CI but the build system.

**Comment by ycombinator** [comment]
@v1v I think the code snippet you posted should suffice. Thanks!

**Comment by ycombinator** [comment]
PRs to resolve this issue:
- For `snapshot` branch: https://github.com/elastic/package-storage/pull/1090
- For `staging` branch: https://github.com/elastic/package-storage/pull/1093
- For `production` branch: TODO

**Comment by mtojek** [comment]
@ycombinator Is there something else to be done or can this be resolved?

**Comment by ycombinator** [comment]
@mtojek Thanks for the ping. This can be resolved now. Closing.
